# webhook admission controller
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kubernetes-cronhpa-service
#  namespace: kube-system
#  labels:
#    app: kubernetes-cronhpa-controller
#spec:
#  selector:
#    app: kubernetes-cronhpa-controller
#  ports:
#  - port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-cronhpa-controller
  namespace: kube-system
  labels:
    app: kubernetes-cronhpa-controller
spec:
  selector:
    matchLabels:
      app: kubernetes-cronhpa-controller
  template:
    metadata:
      labels:
        app: kubernetes-cronhpa-controller
    spec:
      containers:
      - command:
        - /root/kubernetes-cronhpa-controller
        image: jasontomas/kubernetes-cronhpa-controller:v1.0
        imagePullPolicy: Always
        name: kubernetes-cronhpa-controller
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccount: kubernetes-cronhpa-controller
