apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-cronhpa-controller
  namespace: kube-system
  labels:
    app: kubernetes-cronhpa-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-cronhpa-controller
  template:
    metadata:
      labels:
        app: kubernetes-cronhpa-controller
    spec:
      containers:
      - command:
        - /root/kubernetes-cronhpa-controller
        image: jasontomas/kubernetes-cronhpa-controller:v1.5
        imagePullPolicy: IfNotPresent
        name: kubernetes-cronhpa-controller
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccount: kubernetes-cronhpa-controller
